name: Send Other

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  posting:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.4
          bundler-cache: true
      - name: Posting
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_TELEGRAM_ID: ${{ secrets.MY_TG_ID }}
        run: |
          bundle exec inat-channel -c other.yml
      - name: Back push
        uses: jekyll-is/action-jekyll-is-backpush@v1
        with:
          label: 'iNat UN Post'
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-user-id: ${{ secrets.MY_TG_ID }}
